name: Deploy DataHub on EKS using Docker compose file

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: kubernetes-worker

    steps:
      - name: Set up environment
        uses: actions/setup-node@v3
        with:
          node-version: '16'
       
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Update kube config
        run: aws eks update-kubeconfig --name ${{ secrets.EKS_NAME }}   
      
      - name: Install python
        run: |
          python3 -m pip install --upgrade pip wheel setuptools
          python3 -m pip install --upgrade acryl-datahub

      - name: Run Datahub
        run: datahub docker quickstart
        

     
